name = "aoc2022"
description = "Advent of Code 2022"
version = "0.1.0-dev"

authors = ["Andrew Stanton-Nurse"]
maintainers = ["Andrew Stanton-Nurse <contact@analogrelay.net>"]
maintainers-logins = ["analogrelay"]

executables = [
    "day_01",
    "day_02",
    "day_03",
    "day_04",
    "day_05",
    "day_06",
    "day_07",
    "day_08",
    "day_09",
    "day_10",
    "day_11",
    "day_12",
    "day_13",
    "day_14",
    "day_15",
    "day_16",
    "day_17",
    "day_18",
    "day_19",
    "day_20",
    "day_21",
    "day_22",
    "day_23",
    "day_24",
    "day_25",
]
